### ISSUE TITLE
Fix Pagination

### ISSUE THREAD

**Issue by lkitto** [gastate/dalnfrontend#48]

**Comment by CodeFluent** [comment]
https://g00glen00b.be/pagination-component-angular-2/

**Comment by CodeFluent** [comment]
From lisa:

Rather than put the pagination in the PostList component, it makes more sense to make a PagedPosts component which contains PostList and Pagination components and takes all the required inputs. Best to keep the PostList component clean in case you ever want a list not paginated. The PagedPosts component would then be used on the Home component.

**Comment by CodeFluent** [comment]
1ab2a446ae28791d206b7bef3577bfb5ec90d9b2 commit the working branch and change of pagination. Pagination bugs/issues will be dealt with in separate issues like #67.

Closing...
