### ISSUE TITLE
Add Embedded Video for Sprout

### ISSUE THREAD

**Issue by lkitto** [gastate/dalnfrontend#8]
Please add iframe to support Sprout Video

**Comment by CodeFluent** [comment]
Fixed the security token issue. @ShakibAhmed will put assetLocation as videos.sproutvideo.com/embed/***VIDEO ID***.

This will make it so that the assetLocations will now be the embedded code. The security token won't matter.

Also https://mwharker.vids.io/videos/***VIDEO ID*** will still be included for now as a shareable link to only video. It will be up to client to discuss whether or not to include them.

**Comment by CodeFluent** [comment]
#9

**Comment by CodeFluent** [comment]
Video embeds working as of e63aa79b51964a732b6c4e5b31ca53d840b4191a.

Some issues:

    - No fullscreen #9 
    - Weird responses of Sprout API. See the console of the latest push to the dev site: http://daln.s3.amazonaws.com/frontend/index.html
